config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks" }
  
  root 'welcome#index'
  get "/about", to: "welcome#about"

  resources :spigots do
    resources :waterings, only: [:new, :create, :show, :update, :destroy]
    get "/usages", to: "usages#minutes"
    get "/gallons", to: "usages#gallons"
    get '/status', to: "spigots#status"
    patch "/on", to: "spigots#on"
    patch "/off", to: "spigots#off"
  end

end

app/models/spigot.rb
class Spigot < ActiveRecord::Base
  belongs_to :user
  has_many :waterings
  has_many :weather_apis
  has_many :usages
  geocoded_by :address
  after_validation :geocode

  def address
    "#{street_address}, #{city}, #{state}, #{country}"
  end

  def access_days_weather
    weather = weather_apis.where("created_at > ?", Time.now.midnight.utc).first || fetch_days_weather
  end

  def fetch_days_weather 
    response =WeatherApi.current_forecast latitude, longitude
    data = WeatherApi.parse_data response
    weather_apis.create!(data)
  end

  def get_watering_schedule
    data =waterings.all.order(start_time: :asc)
    days = %w(monday tuesday wednesday thursday friday saturday sunday)
    schedule =
    {
      monday: [],
      tuesday: [],
      wednesday: [],
      thursday: [],
      friday: [],
      saturday: [],
      sunday: []
    }
    data.each do |watering|
      days.each do |day|
        if watering[day]
          schedule[day.to_sym].push(
            "#{watering.parse_time watering.start_time} - #{watering.parse_time watering.end_time}", 
            watering.id
            )
        end
      end
    end
    schedule[:count] = find_max schedule
    schedule
  end

  def turn_on? 
    weekday = get_day
    waters = waterings.where("#{weekday}": true).all
    waters.each do |water|
      t = water.start_time
      Time.zone = timezone
      hour =Time.zone.now.hour
      minute = Time.zone.now.min
      if hour == t.getlocal.hour && minute == t.getlocal.min
        usage = get_usage
        if not_rainy?
          self.on
          usage.minutes += (water.duration / 60)
          usage.save!
        else
          usage.water_saved += (water.duration / 60)
          usage.overrides += 1
          usage.save!
        end
      end
    end
  end

  def turn_off? 
    weekday = get_day
    waters = waterings.where("#{weekday}": true).all
    waters.each do |water|
      t = water.end_time
      Time.zone = timezone
      hour = Time.zone.now.hour
      minute = Time.zone.now.min
      if hour == t.getlocal.hour && minute == t.getlocal.min
        self.off
      end
    end
  end

  def get_day
    Time.zone = timezone
    weekday = Time.zone.now.strftime('%A').downcase
  end

  def on 
    HTTParty.get("http://172.30.23.254:70/L")
    update status:"On"
  end

  def off
    HTTParty.get("http://172.30.23.254:70/H")
    update status: "Off"
  end

  def get_usage
    usages.where("created_at > ?", Time.now.midnight.utc).first_or_create!(
      minutes: 0, 
      water_saved: 0,
      overrides: 0, 
      wday: get_day,
      day: Time.now.day,
      month: Time.now.month,
      year: Time.now.year
      )
  end

  def not_rainy?
    weather = access_days_weather
    weather.precip_chance < threshold
  end

  private

  def find_max schedule
    max =0
    schedule.each_value do |v|
      if v.count > max 
        max= v.count 
      end
    end
    max/2
  end


end

app/controllers/spigots_controller.rb
class SpigotsController < ApplicationController
  def new
    @spigot = Spigot.new
  end

  def create
    @spigot = current_user.spigots.create(
      name: params['spigot'][:name], 
      ip: params['spigot']['ip'], 
      street_address: params['spigot']['street_address'],
      city: params['spigot']['city'],
      state: params['spigot']['state'],
      country: params['spigot']['country'],
      zipcode: params['spigot']["zipcode"],
      timezone: params["spigot"]['timezone'],
      threshold: params['spigot']['threshold']
      )
    redirect_to spigot_path @spigot
  end

  def show
    @spigot =Spigot.find(params['id'])
    @status = @spigot.status
    @weather =@spigot.access_days_weather
    @watering_days =@spigot.get_watering_schedule
  end

  def index
    @spigots = current_user.spigots.all
  end

  def update
    @spigot =Spigot.find(params['id'])
    @spigot.update! name: params["spigot"]['name'], threshold: params['spigot']['threshold']
    redirect_to :back, alert:"Spigot Updated"
  end

  def on
    @spigot = Spigot.find(params['spigot_id'])
    @spigot.on
    redirect_to :back, alert: "Spigot Turned On"
  end

  def off
    @spigot = Spigot.find(params['spigot_id'])
    @spigot.off
    redirect_to :back, alert: "Spigot Turned Off"
  end

  def status
    @spigot = Spigot.find(params['spigot_id'])
    render json: {
      status: @spigot.status
    }
  end

end

app/helpers/spigots_helper.rb
module SpigotsHelper
end

app/views/spigots/index.html.slim
div class="container"
  div class='col-md-4'
  div class='col-md-4'
    div 
      h3 class="alert alert-success" style="text-align:center" Spigots
    table class='table table-bordered table-striped'
      thead 
        tr
          th Name
          th Status
      tbody
        -@spigots.each do |spigot|
          tr
            td
              a href=spigot_path(id:spigot) =spigot.name
            td=spigot.status

app/views/spigots/new.html.slim
div class="container"
  div class="col-md-3"
  div class="well col-md-6"
    =form_for @spigot, action: "create", html: {class:"form-horizontal"} do |s|
      legend Register a New Spigot
      div class="form-group"
        =s.label :name, "Name: ", class: "col-lg-4 control-label"
        =s.text_field :name, class: "col-lg-5"
      div class="form-group"
        =s.label :ip, "IP Address:", class: "col-lg-4 control-label"
        =s.text_field :ip, class: "col-lg-5"
      div class="form-group"
        =s.label :street_address, "Street Address: ", class: "col-lg-4 control-label"
        =s.text_field :street_address, class: "col-lg-5"
      div class="form-group"
        =s.label :city, "City: ", class: "col-lg-4 control-label"
        =s.text_field :city, class: "col-lg-5"
      div class="form-group"
        =s.label :state, "State: ", class: "col-lg-4 control-label"
        =s.text_field :state, class: "col-lg-5"
      div class="form-group"
        =s.label :country, "Country: ", class: "col-lg-4 control-label"
        =s.text_field :country, class: "col-lg-5"
      div class="form-group"
        =s.label :zipcode, "Zipcode: ", class: "col-lg-4 control-label"
        =s.text_field :zipcode, class: "col-lg-5"
      div class="form-group"
        =s.label :timezone, "Time Zone", class: "col-lg-4 control-label"
        =s.time_zone_select :timezone
      div class="form-group"
        =s.label :threshold, "Rain Threshold:", class: "col-lg-4 control-label"
        =s.text_field :threshold
      =s.submit class:"btn btn-success"
  div class='col-md-3'

app/views/spigots/show.html.slim
input id= "spigotId" type="hidden" value="#{@spigot.id}"
input id="spigotStatus"  type="hidden" value="#{@status}"
div class='container'
  div class='col-md-9'
    div class='panel panel-primary'
      div class= 'panel-heading'
        div class='panel-title'= "Spigot: #{@spigot.name}"
      div class='panel-body'
        div class="col-md-8"
          h3= "City: #{@spigot.city}"
          h3= "Status: #{@status}"
          h3= "Rain Threshold: #{@spigot.threshold}%"
        div class="col-md-4"
          br
          br
          br
          div class="btn-group" role="group" aria-label="On and Off"
            -if @spigot.status == "On"
              =link_to "Turn Off", {action: "off",spigot_id: @spigot.id}, method: :patch, type: "button",class: "btn btn-danger btn-lg"
            -else
              =link_to "Turn On", {action: "on", spigot_id: @spigot.id}, method: :patch, type: "button", class: "btn btn-success btn-lg" 
    div class="panel panel-primary"
      div class='panel-heading'
        div class='panel-title'= "Schedule (Click the watering to see its schedule)"
      div class='panel-body'
        table class='table table-bordered table-condensed' width='400'
            -days =%w(monday tuesday wednesday thursday friday saturday sunday)
            thead
              tr
                -days.each do |day|
                  th= day.upcase
            tbody
              -x = 0
              -@watering_days[:count].times do ||
                tr
                  -days.each do |day|
                    td
                      -if @watering_days[day.to_sym].count >= x+1
                       =link_to "#{@watering_days[day.to_sym][x]}", spigot_watering_path(spigot_id: @spigot, id: @watering_days[day.to_sym][x+1])
                      -else
                        ="___________"
                -x += 2            
    div class= 'row' 
      div class= 'panel panel-warning' 
        div class='panel-heading'
          div class='panel-title' Usage History
        div class='panel-body'
          div class="col-md-4"
            h5 Minutes of Watering per day
            canvas id="myChart" width="300" height="300" style="background-color: white;"
            div class="legend"
              ul
                li
                  span.color-badge style="background-color:rgba(215, 40, 40, 1);" &nbsp&nbsp&nbsp
                  span &nbsp Minutes Running
                li
                  span.color-badge style="background-color:rgba(0, 133, 0, 1);" &nbsp&nbsp&nbsp
                  span &nbsp Minutes Overidden  

          div class="col-md-2"
          div class='col-md-4'
            h5 Gallons used per month
            canvas id="secondChart" width="300" height="300" style="background-color: white;"
                javascript:
                  var chart_data, myLineChart
                  var spigot = "#{@spigot.id}";
                  var ctx = document.getElementById("myChart").getContext("2d");
                  

                  $.ajax( "/spigots/" + spigot +"/usages", {
                    method: "GET",
                    success: function(data){
                      console.log(data.data.used)
                      chart_data ={
                        labels: data.data.labels,
                        datasets: [
                          {
                            label: "Water Usage in Minutes",
                            fillColor: "rgba(215, 40, 40, 0.2)",
                            strokeColor: "rgba(215, 40, 40, 1)",
                            pointColor: "rgba(215, 40, 40, 1)",
                            pointStrokeColor: "#000",
                            pointHighlightFill: "#000",
                            pointHighlightStroke: "rgba(215, 40, 40, 1)",
                            data: data.data.used.data
                            },
                          {
                            label: "Water Saved in Minutes",
                            fillColor: "rgba(0, 133, 0, 0.2)",
                            strokeColor: "rgba(0, 133, 0, 1)",
                            pointColor: "rgba(0, 133, 0, 1)",
                            pointStrokeColor: "#000",
                            pointHighlightFill: "#000",
                            pointHighlightStroke: "rgba(0, 133, 0, 1)",
                            data: data.data.saved.data
                            }       
                           ]
                      };

                      myLineChart = new Chart(ctx).Line(chart_data);
  
                    }
                  });
                  var chart_data, myBarChart;
                  var barctx = document.getElementById("secondChart").getContext("2d");
                  $.ajax( "/spigots/" + spigot +"/gallons", {
                  method: "GET",
                  success: function(data){
                    chart_data ={
                      labels: data.data.labels,
                      datasets: [
                        {
                          label: "Water Usage in Gallons",
                          fillColor: "rgba(151,187,205,0.5)",
                          strokeColor: "rgba(151,187,205,0.8)",
                          highlightFill: "rgba(151,187,205,0.75)",
                          highlightStroke: "rgba(151,187,205,1)",
                          data: data.data.numbers
                        }      
                      ]
                    };

                    myBarChart = new Chart(barctx).Bar(chart_data);
                    }
                  }); 
            
               
              

  div class= 'col-md-3'
    div class='panel panel-info'
      div class= 'panel-heading'
        h1 class='panel-title'= "Weather for #{Time.now.month}/#{Time.now.day}"
      div class='panel-body'
        h4="Chance of Rain: #{@weather.precip_chance}%"
        h4="Predicted High: #{@weather.temp_max}°F"
        h4="Predicted Low: #{@weather.temp_min}°F"
    =link_to "Schedule a new watering", new_spigot_watering_path(spigot_id: @spigot), class:"btn btn-success btn-lg"
    br
    br
    =form_for @spigot, method: 'PATCH', html: {class:"form"} do |f|
      legend Edit Spigot
      div class="form-group"
        =f.label :name, class: "col-md-4 control-label"
        =f.text_field :name
      div class="form-group"
        =f.label :threshold, class: "col-md-4 control-label"
        =f.text_field :threshold
      =f.submit class: "btn btn-sucess"