config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks" }
  
  root 'welcome#index'
  get "/about", to: "welcome#about"

  resources :spigots do
    resources :waterings, only: [:new, :create, :show, :update, :destroy]
    get "/usages", to: "usages#minutes"
    get "/gallons", to: "usages#gallons"
    get '/status', to: "spigots#status"
    patch "/on", to: "spigots#on"
    patch "/off", to: "spigots#off"
  end

end

app/models/watering.rb
class Watering < ActiveRecord::Base
  belongs_to :spigot

  def parse_time time 
    time.getlocal.strftime("%I:%M%p")
  end

  def self.to_utc hour, minute
    time = Time.now(2000,1,1, hour, minute)
  end



end

app/controllers/waterings_controller.rb
class WateringsController < ApplicationController
  
  def new
    @watering=Watering.new
    @spigot = Spigot.find(params[:spigot_id])
  end

  def create
    @spigot = Spigot.find(params['spigot_id'])
    data = params['watering']
    start_time = Time.new(2000, 1, 1,data['start_time(4i)'], data['start_time(5i)'])
    end_time = Time.new(2000,1,1,data['end_time(4i)'], data['end_time(5i)'])
    if end_time < start_time
      redirect_to :back, alert: "End Time must occur after Start Time"
    else
      @spigot.waterings.create( 
        start_time: start_time, 
        end_time: end_time,
        duration: end_time - start_time,
        monday: data['monday'],
        tuesday: data['tuesday'],
        wednesday: data['wednesday'],
        thursday: data['thursday'],
        friday: data['friday'],
        saturday: data['saturday'],
        sunday: data['sunday'])
      redirect_to spigot_path @spigot
    end
  end

  def show
    @watering = Watering.find(params[:id])
    @start_time = @watering.parse_time @watering.start_time
    @end_time = @watering.parse_time @watering.end_time
  end

  def update
    @spigot = Spigot.find(params[:spigot_id])
    @watering = Watering.find(params[:id])
    data = params["watering"]
    @watering.update(
      start_time: data["start_time"],
      end_time: data["end_time"],
      monday: data['monday'],
      tuesday: data['tuesday'],
      wednesday: data['wednesday'],
      thursday: data['thursday'],
      friday: data['friday'],
      saturday: data['saturday'],
      sunday: data['sunday']
      ) 
    redirect_to spigot_watering_path, spigot_id: @spigot, id: @watering
  end

  def destroy
    Watering.find(params['id']).delete
    redirect_to spigot_path id: params['spigot_id']
  end
end

app/helpers/waterings_helper.rb
module WateringsHelper
end

app/views/waterings/new.html.slim
div class= "container"
  div class="col-md-4"
  div class="well col-md-4"
    =form_for @watering, url: spigot_waterings_path, html: {class: "form"} do |w|
      legend Create a new Watering
      div class= "form-group"
        =w.label :start_time, class: "col-lg-4 control-label"
        =w.time_select :start_time, ampm:true, default: {hour: 12}
      div class= "form-group"
        =w.label :end_time, class: "col-lg-4 control-label"
        =w.time_select :end_time, ampm:true, minute_step: 15, default: {hour: 12}
      -days = %w(monday tuesday wednesday thursday friday saturday sunday)
      table class="table table-bordered"
        thead
          tr
            th M
            th T
            th W
            th T
            th F
            th S
            th S
        tbody
          tr
            -days.each do |d|
              td 
                div class="form-group"
                  =w.check_box d.to_sym, {checked: false, id:"wateringDays"}, "true", "false"
      =w.submit "Submit", class: 'btn btn-primary'

app/views/waterings/show.html.slim
div class="container"

  h3 = "Start Time: #{@start_time}"
  h3 ="End Time: #{@end_time}"
  table class="table table-bordered"
    thead
      tr
        th Monday
        th Tuesday
        th Wednesday
        th Thursday
        th Friday
        th Saturday
        th Sunday
    tbody
      tr
        -days = %w(monday tuesday wednesday thursday friday saturday sunday)
        -days.each do |day|
          -if @watering[day] == true
            td 
              span class="glyphicon glyphicon-ok" aria-hidden="true"
          -else
            td
              span class="glyphicon glyphicon-remove" aria-hidden="true"

  =button_to "Delete Watering", { action: "destroy", spigot_id: params['spigot_id'], id: @watering }, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"