config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks" }
  
  root 'welcome#index'
  get "/about", to: "welcome#about"

  resources :spigots do
    resources :waterings, only: [:new, :create, :show, :update, :destroy]
    get "/usages", to: "usages#minutes"
    get "/gallons", to: "usages#gallons"
    get '/status', to: "spigots#status"
    patch "/on", to: "spigots#on"
    patch "/off", to: "spigots#off"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmartSpigot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://bootswatch.com/slate/bootstrap.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "navbar navbar-default">
    <div class ="container">
      <div class="navbar-header">
        <% if user_signed_in? %>
          <div class="navbar-brand">Signed in as <%= current_user.email %></div>
        <%else %>
        <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %>
        <% end %>
      </div>
      <div class="navbar-collapse collapse" id="navbar-main">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path,:method => :delete %><li>
          <li><%= link_to "Home", root_path %><li>
          <li><%= link_to "About", about_path %><li>
          <li><%= link_to "Spigots", spigots_path %><li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class= "container">
    <% if alert %>
      <p class="alert alert-success"><%= alert %></p>
    <%end %>
  </div>
<%= yield %>
</body>
</html>